version: '3.3'

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./html:/var/www/html #프로젝트 경로
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf #nginx 설정 파일

    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_HOST: localhost
            MYSQL_DATABASE: dbname #디비명
            MYSQL_USER: user #사용자명
            MYSQL_PASSWORD: password #사용자비밀번호
            MYSQL_ROOT_PASSWORD: password #루트계정비밀번호
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql

    php:
        image: php:7.4-fpm
        container_name: php
        volumes:
            - ./html:/var/www/html #프로젝트 경로
        ports:
            - "9000:9000"
        command:
            - /bin/sh
            - -c
            - |
              echo "security.limit_extensions = .php .phtml .php3 .php4 .php5 .html .htm" >> /usr/local/etc/php-fpm.d/www.conf
              php-fpm

   phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        links:
            - mysql
        environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
        restart: always
        ports:
        - 8081:80
